[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[start]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONUNBUFFERED = "1"

[env]
root = "server"
